# AuthEngine reverse proxy — HTTP only (certbot adds HTTPS blocks)
# Generated by auth-engine-deploy.sh — do not edit on EC2; re-run: ./deploy/auth-engine-deploy.sh nginx

# API + IdP → :8000
server {
    listen 80;
    server_name @API_HOST@ @IDP_HOST@;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

# Dashboard → :3000
server {
    listen 80;
    server_name @APP_HOST@;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

# Apex → app (HTTP redirect until certbot adds HTTPS)
server {
    listen 80;
    server_name @ROOT_DOMAIN@ www.@ROOT_DOMAIN@;

    location / {
        return 302 http://@APP_HOST@$request_uri;
    }
}
