apiVersion: v1
kind: Secret
metadata:
  name: authengine-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  MONGO_PASSWORD: {{ .Values.secrets.mongoPassword | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | quote }}
  POSTGRES_URL: "postgresql+asyncpg://postgres:{{ .Values.secrets.postgresPassword }}@postgres-service:5432/authengine"
  MONGODB_URL: "mongodb://root:{{ .Values.secrets.mongoPassword }}@mongodb-service:27017/authengine?authSource=admin"
  REDIS_URL: "redis://:{{ .Values.secrets.redisPassword }}@redis-service:6379/0"
  APP_URL: "https://{{ .Values.global.idpSubdomain }}.{{ .Values.global.domain }}"
  DASHBOARD_URL: "https://{{ .Values.global.dashboardSubdomain }}.{{ .Values.global.domain }}"
  WEBAUTHN_RP_ID: {{ .Values.global.domain | quote }}
  CORS_ORIGINS: '["https://{{ .Values.global.dashboardSubdomain }}.{{ .Values.global.domain }}"]'
  RESEND_API_KEY: {{ .Values.secrets.resendApiKey | quote }}
  EMAIL_SENDER: "noreply@{{ .Values.global.domain }}"
